### ISSUE TITLE
Cannot find module `./Base64` from `lib/websock.js`

### ISSUE THREAD

**Issue by julien-f** [eface2face/noVNC-node#2]
And btw, why is there a `lib/base64.js` file while this package depends on `base64-js`?

**Comment by ibc** [comment]
Thanks, it is fixed.

Initially I tried "base64-js" library but finally did not use it.

And it is funny: the error you have reported about "lib/Base64.js" did not happen to me because OSX's filesystem is case insensitive :)

**Comment by julien-f** [comment]
Thanks for this quick fix :)
